/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.cad.profesor;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.edu.cad.controller.Catalogo;
import sv.edu.cad.model.Conexion;

/**
 *
 * @author Wilber
 */
public class renovacion_profesor extends javax.swing.JInternalFrame {

    /**
     * Creates new form renovacion_profesor
     */
    
    String Carnetcito;
    
    public renovacion_profesor(String carnet) {
        initComponents();
        Carnetcito = carnet;
        llenar_tabladedatos(Carnetcito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        Renovacion = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Carnet", "ID Ejemplar", "Titulo", "Tema", "Nombre Autor", "Apellido Autor", "Material", "ID Prestamo", "Fecha Devolucion", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        Renovacion.setText("Renovar Prestamo");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Renovacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Renovacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        try
        {
            int resp = JOptionPane.showConfirmDialog(this, "¿Está seguro?");
            if(resp == JOptionPane.YES_OPTION)
            {
                this.dispose();
            }
        }
        catch(Exception e)
        {
            Logger.getLogger(Consultar.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void llenar_tabladedatos(String carnetcito)
    {
          try{
           Conexion conexion = new Conexion();
            String sql = "Select usuario.Carnet, ejemplar.idEjemplar, catalogo.Titulo, tema.Tema, autor.Nombre, autor.Apellido, material.NombreMaterial, prestamo.idPrestamo, prestamo.FechaDevolucion, estado.Estado " +
                         "From usuario, catalogo, tema, material, estado, autor, prestamo, ejemplar where usuario.Carnet = '" + carnetcito + "' and estado.Estado = 'PRESTADO'";
            tabladatos.removeAll();
            String columna[] = {"Carnet", "ID Ejemplar","Titulo", "Tema", "Nombre Autor", "Apellido Autor" ,"Material","ID Prestamo","Fecha Devolucion", "Estado"};
            DefaultTableModel tabladatosmod = new DefaultTableModel(null,columna);
            conexion.setRs(sql);
            ResultSet resultadito = conexion.getRs();
            Object datos[] = new Object[10];
            while(resultadito.next()){
               for(int i = 0; i < 10; i++)
               {
                   datos[i] = resultadito.getObject(i + 1);
               }
               tabladatosmod.addRow(datos);
            }
            resultadito.close();
            conexion.cerrarConexion();
            tabladatos.setModel(tabladatosmod);
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(Catalogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Renovacion;
    private javax.swing.JButton cancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladatos;
    // End of variables declaration//GEN-END:variables
}
