/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.cad.profesor;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.edu.cad.controller.Catalogo;
import sv.edu.cad.model.Conexion;

/**
 *
 * @author Wilber
 */
public class renovarprof extends javax.swing.JInternalFrame {

    /**
     * Creates new form renovarprof
     */
    String Carnetcito;
    public renovarprof(String carnet) {
        initComponents();
        Carnetcito = carnet;
        llenar_tabladedatos(Carnetcito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        BCancelar = new javax.swing.JButton();

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Carnet", "Titulo", "Tema", "Nombre Autor", "Apellido Autor", "Material", "Fecha Prestamo", "Fecha Devolucion", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        // TODO add your handling code here:
        try
        {
            int resp = JOptionPane.showConfirmDialog(this, "¿Está seguro?");
            if(resp == JOptionPane.YES_OPTION)
            {
                this.dispose();
            }
        }
        catch(Exception e)
        {
            Logger.getLogger(Consultar.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_BCancelarActionPerformed

    private void llenar_tabladedatos(String carnetcito)
    {
          try{
           Conexion conexion = new Conexion();
            String sql = "Select usuario.Carnet, catalogo.Titulo, tema.Tema, autor.Nombre, autor.Apellido, material.NombreMaterial, prestamo.FechaPrestamo, prestamo.FechaDevolucion, estado.Estado " +
                         "From usuario, catalogo, tema, material, estado, autor, prestamo where usuario.Carnet = '" + carnetcito + "'";
            tabladatos.removeAll();
            String columna[] = {"Carnet","Titulo", "Tema", "Nombre Autor", "Apellido Autor" ,"Material","Fecha Prestamo","Fecha Devolucion", "Estado"};
            DefaultTableModel tabladatosmod = new DefaultTableModel(null,columna);
            conexion.setRs(sql);
            ResultSet resultadito = conexion.getRs();
            Object datos[] = new Object[9];
            while(resultadito.next()){
               for(int i = 0; i < 9; i++)
               {
                   datos[i] = resultadito.getObject(i + 1);
               }
               tabladatosmod.addRow(datos);
            }
            resultadito.close();
            conexion.cerrarConexion();
            tabladatos.setModel(tabladatosmod);
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(Catalogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladatos;
    // End of variables declaration//GEN-END:variables
}
